apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PzdspVDzFgJnDKg=,iv:ZxDTdkOANlGZ4xsaUKQHiNV1XHnt3Vzw6OrnH9fxfbk=,tag:LeKhD/oS1BEoluHyt77neA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NQ8rVP8vc+W8PHcO7oqNdi9XQKlvL6NeuHXOdXAMD7NOk7CR,iv:afjogBLtSpvCqcaLhCjmem4kMAJprOH3HivRBVSux6Y=,tag:JXewDZ+G7B/7e2wpTcfK2A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12kpvh739q9vhk9wvvfcr90qmu6xgvnvxuufx8nye0d4qus37u4jqrqgm83
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSmhsampGOU8xTmtFTHNZ
        RlZPclhnS1RHZHJBbDFNR01oVXNqVlZhaTFnCjZId3hGR2kwRUdObk1XUzB1aHR0
        a3NGenY1WEVyY25IdmJzd1hzT0oyemMKLS0tIE95RFlwdldXdnU2M09rWCtrQkpS
        dVMvMEpUT2hqTHpkZUwwREhleUlwdHcKdEX1zNx9aZ1kqOn5cNij4D/VdKzeALzS
        bXe5Pqzyf+ERpyLooQw7eOfxkJ0tCXtqP+EdBaG58hZtG3UgXJ/BVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-15T16:48:53Z"
  mac: ENC[AES256_GCM,data:AfWABo0XiRJgwG0CI6++wu9ifvne4ozVfAiM7m4tcb68aBJd5Mq9yJXkB4kwNnumlLhctF018YYxoyMrKuaJy3BwlNpAwaoXyUcu3IZcyJOHSjlUGA0hpSW3s0FIhc/15agliN9Cqs4WUklmHFpwxe881E7ZYCyq1Z+sK3s2H2Q=,iv:sHite0za0QAIAmCXI473lnZxBmr03vvgi6p9ETlahfs=,tag:cV03l9sx+0Ag/ROga3cXCQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
